export const ingredients: string[] = [
  "spaghetti",
  "ground beef",
  "onion",
  "garlic",
  "tomato sauce",
  "olive oil",
  "salt",
  "pepper",
  "chicken",
  "ginger",
  "curry powder",
  "coconut milk",
  "vegetable oil",
  "tortillas",
  "tomato",
  "lettuce",
  "cheese",
  "sour cream",
  "guacamole",
  "sushi rice",
  "nori",
  "fish (e.g., salmon, tuna)",
  "avocado",
  "cucumber",
  "soy sauce",
  "wasabi",
  "pickled ginger",
  "burger buns",
  "ketchup",
  "mustard",
  "rice noodles",
  "shrimp",
  "tofu",
  "egg",
  "bean sprouts",
  "green onions",
  "peanuts",
  "lime",
  "fish sauce",
  "lasagna noodles",
  "ricotta cheese",
  "mozzarella cheese",
  "parmesan cheese",
  "cooked chicken",
  "salsa verde",
  "cilantro",
  "beef",
  "bell peppers",
  "broccoli",
  "carrots",
  "sesame oil",
  "potatoes",
  "eggplant",
  "béchamel sauce",
  "cinnamon",
];

export const nationalities: string[] = [
  "Japanese",
  "Greek",
  "French",
  "Italian",
  "Thai",
  "Mexican",
  "Chinese",
  "American",
];
